
# include makefile basic
include ../include_makefile/basic.mk
include ../include_makefile/tools.mk

# Project Name or Library Name 
PRO_EXE := $(BIN_DIR)$(notdir $(shell pwd)).exe
PRO_LIB := 

# Libraries references
LIB_REFERENCES := $(BIN_DIR)common.a $(BIN_DIR)extractfeature.a $(BIN_DIR)getneighbor.a $(BIN_DIR)lshtc_lib.a

# include makefile main
include ../include_makefile/makefile.mk
