
# include makefile basic
include ../include_makefile/basic.mk

# Project Name or Library Name 
PRO_EXE := $(BIN_DIR)$(notdir $(shell pwd)).exe
PRO_LIB := 

# Libraries references
LIB_REFERENCES := 

# include makefile main
include ../include_makefile/makefile.mk
