
# include makefile basic
include ../include_makefile/basic.mk

# Project Name or Library Name 
PRO_EXE := 
PRO_LIB := $(BIN_DIR)$(notdir $(shell pwd)).a

# Libraries references
LIB_REFERENCES := 

# include makefile main
include ../include_makefile/makefile.mk
